# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7.0

jobs:
  Linting:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run lint
          command: npm run lint

  Firefox integration tests:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      - run:
          name: Install Firefox, and dependencies for official Google Chrome package
          command: sudo apt update && sudo apt install firefox fonts-liberation libgbm1 xdg-utils libnspr4 libnss3
      - run:
          name: Download and install official Google Chrome package
          command: wget 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' && sudo dpkg -i google-chrome-stable_current_amd64.deb
      - run:
          name: Run Selenium tests
          command: export PATH=.:$PATH && npm run test:integration

workflows:
  version: 2
  ci:
    jobs:
      - Linting
      - Firefox integration tests
